---

gradientMode: "hue"
cellIdPreamble: "cell-"
cells:
  inhouse_queue_depth:
    dataRef: elem
    fillColor:
      thresholds:
        - color: green
          level: 0
  inhouse_queue_count:
    dataRef: elem2
    fillColor:
      thresholds:
        - color: green
          level: 0
  rabbitmq_queue_depth:
    dataRef: elem3
    fillColor:
      thresholds:
        - color: green
          level: 0
