---
gradientMode: "hue"
cellIdPreamble: "cell-"
cells:
  fuel_consumption:
    dataRef: "fuel consumption"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  running_hours:
    dataRef: "running hours"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
  load:
    dataRef: "load"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  speed:
    dataRef: "speed"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
  distance:
    dataRef: "distance"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
 
