---
gradientMode: "hue"
cellIdPreamble: "cell-"
cells:
  elem:
    dataRef: "elem"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  elem2:
    dataRef: "elem2"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
  elem3:
    dataRef: "elem3"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  rabbitmq_queue_count:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuecount"
    linkRef: "grafana-home"
  mem_queue_depth:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "queuedepth"
    linkRef: "grafana-home"
  db_transactions:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "dbtrans"
    linkRef: "grafana-home"
  duplicate_lock_rate:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "dbtrans"
    linkRef: "grafana-home"
  inhouse_queue_latency:
    dataRef: "test-data-small-sin"
    label:
      separator: "cr"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
  wakeup_queue_latency:
    dataRef: "test-data-small-sin"
    label:
      separator: "cr"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
  rabbitmq_latency:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
  rabbitmq_slowness:
    dataRef: "test-data-small-cos"
    label:
      separator: "space"
      units: "s"
      decimalPoints: 1
    labelColor:
      thresholdsRef: "queuelatency"
    linkRef: "grafana-home"
